"""Dump all filter prompts across measures into a single readable markdown file.

Stage 1 is identical across all measures, so it is shown once at the top.
Stage 3 and Stage 4 share the same `system_prompt` (only the model differs:
GPT-4o-mini vs Claude Opus 4.6), so only Stage 3 is shown.

Usage:
    uv run python scripts/dump_prompts.py [--output PROMPTS.md]
"""

import argparse
import json
from pathlib import Path

MEASURE_DIR = Path("src/filter/measure")


def render_value(value) -> str:
    """Render a JSON value as a fenced code block."""
    if isinstance(value, str):
        return f"```\n{value}\n```"
    return f"```json\n{json.dumps(value, indent=2, ensure_ascii=False)}\n```"


def render_filter_file(path: Path) -> str:
    data = json.loads(path.read_text())
    lines = []
    for key, value in data.items():
        lines.append(f"**`{key}`**\n")
        lines.append(render_value(value))
        lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="PROMPTS.md")
    args = parser.parse_args()

    measures = sorted(
        p.name for p in MEASURE_DIR.iterdir()
        if p.is_dir()
        and not p.name.startswith("_")
        and p.name not in ("base", "obsolete")
    )

    out = []
    out.append("# Filter Prompts\n")
    out.append(
        "Auto-generated by `scripts/dump_prompts.py` — do not edit by hand. "
        "Re-run the script to refresh after changing any `filterN.json`.\n"
    )
    out.append(
        "**Notes:**\n"
        "- Stage 1 (coarse filter) is identical across all measures and is shown once below.\n"
        "- Stage 3 (GPT-4o-mini) and Stage 4 (Claude Opus 4.6) share the same `system_prompt`; only the model differs. Only Stage 3 is shown per measure.\n"
    )
    out.append(f"Measures: {len(measures)}\n")

    # Shared Stage 1
    out.append("## Stage 1 — Coarse Filter (vLLM, Qwen3-VL-8B) — shared across all measures\n")
    out.append(render_filter_file(MEASURE_DIR / measures[0] / "filter1.json"))

    out.append("\n## Table of Contents\n")
    for m in measures:
        anchor = m.lower().replace("_", "-")
        out.append(f"- [{m}](#{anchor})")
    out.append("")

    for measure in measures:
        out.append(f"\n---\n\n## {measure}\n")

        out.append("### Stage 2 — Low-Quality Filter (vLLM, Qwen3-VL-8B)\n")
        out.append(render_filter_file(MEASURE_DIR / measure / "filter2.json"))

        out.append("### Stage 3 — High-Quality / Final Filter (GPT-4o-mini at Stage 3, Claude Opus 4.6 at Stage 4)\n")
        out.append(render_filter_file(MEASURE_DIR / measure / "filter3.json"))

    Path(args.output).write_text("\n".join(out))
    print(f"Wrote {args.output} ({len(measures)} measures)")


if __name__ == "__main__":
    main()
